name: Deploy API

on:
  workflow_dispatch:
  push:
    branches:
        - master

env:
  AZURE_WEBAPP_NAME: "onelabwebapp"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install .net core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: install depedencies
        run: dotnet restore ./helloApi/helloApi.csproj

      - name: build 
        run: dotnet build ./helloApi/helloApi.csproj --configuration Release --no-restore

      - name: publish
        run: dotnet publish ./helloApi/helloApi.csproj --configuration Release --output ./publish

      - name: deploy to azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ./publish